### ISSUE TITLE
"Asatir 2: Mirai no Mukashi Banashi" has wrong AniDB url

### ISSUE THREAD

**Issue by TomaraRedfox** [manami-project/anime-offline-database#100]
### Have you read the FAQ?

- [X] Yes I have read the FAQ

### Meta data provider

anidb.net

### Affected properties

sources

### Example

https://anidb.net/anime/15489

### Expected value

https://anidb.net/anime/18964

**Comment by manami-project** [comment]
I don't see anything wrong with the extraction.
Maybe you mean to create either a split or merge request?
