### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by BeeeQueue** [manami-project/anime-offline-database#16]
I created a REST server that returns the data in this repo in JSON form.
It fetches and caches the data in a database once per day, and is available at [https://relations.yuna.moe](https://relations.yuna.moe) ([Github](https://github.com/BeeeQueue/arm-server)).

Would it be a good idea to add it to the readme of this repo?

**Comment by MrHDOLEK** [comment]
Yes i think a good idea to add this repo.I must be learn a json to made my
project a anime database website.Thanks a reply

wt., 11 cze 2019 o 22:13 Adam Haglund <notifications@github.com> napisał(a):

**Comment by manami-project** [comment]
@BeeeQueue Let me think about this.

**Comment by manami-project** [comment]
I think you have something like an [awsome list](https://github.com/sindresorhus/awesome) in mind?
Personally I would like to keep the README.md informative and strictly about the project itself.

This is something for either a curated list either in a separate repo or the topics on github.

**Comment by BeeeQueue** [comment]
No, I was just thinking that if anyone wants easy access to the data in this project without downloading the files and keeping it updated it would be nice to have another interface for it. 

It's the same data, just another way to fetch/read it.

If you think this is unnecessary that's fine, it was just an idea I had.

**Comment by manami-project** [comment]
I see your point, but I have to see it from a more general perspective. If I add your REST-API, others might ask to add their project too. I know that @MWGuy created a desktop app for example, @Xetera had a search engine if I remember correctly and so on. There are quite a few other projects depending on this database as far as I know. So this might lead to a this kind of curated awesome list in a very small context I was talking about.

I am really not sure on this one. Any more opinions? Should other projects relying on this database be added to the README.md?

**Comment by Xetera** [comment]
I think the point of this repo is supposed to be based around offline access, so these side projects dont really align with the main goal here if you ask me. It wouldn't make sense to have a specific section for a rest api.

If you're ok with like a small "here's what the community has done with this repo" sort of thing on the side, it would probably be more appropriate. 👍

**Comment by BeeeQueue** [comment]
Just to clarify, I'm not asking about a giant REST API section in the readme. What I meant was something like a "projects using this data" section.

**Comment by manami-project** [comment]
I decided to try it and added contribution guidelines.
