### ISSUE TITLE
Character database?

### ISSUE THREAD

**Issue by Xetera** [manami-project/anime-offline-database#17]
This seems infeasible given the amount of effort it would take to maintain it but would it be possible to add a separate database for characters too? This repo is extremely useful for me but an offline list of characters would be even more useful for what I'm trying to do.

Depending on how this is implemented, it could be possible to write a script to fetch characters from newly-added animes in the database. If this is something you're interested in I'd be happy to give it a shot and see how big the json for this could get if not, that's okay too.

**Comment by adminy** [comment]
Have you tried using anidb API? I know it’s in XML format but there are plenty of XML to JSON converters out there.

**Comment by Xetera** [comment]
I'm looking to implement auto-complete for character names and I'm not entirely sure how I feel about hitting a public API for something like that. Sounds like I'd get rate-limited very quickly.

**Comment by adminy** [comment]
I use the API if my database hasn’t got the particular entry. But it’s just names you’re looking for 🤔? (I have hit the rate limits and the ban is up to a month of waiting or change your ip) if it’s just names I might have that.

**Comment by floflo2607** [comment]
You can do hit by fetching all anime character in kitsu with their api.
https://kitsu.docs.apiary.io/ 
You can have unlimited requests with proxy

**Comment by MrHDOLEK** [comment]
I have not tried to use this api anidb but it looks interesting.
There is also the possibility that if you convert from json to xml it may
contain many errors but it is unrelated to the application, etc.

czw., 13 cze 2019 o 13:00 flo <notifications@github.com> napisał(a):

**Comment by adminy** [comment]
@MrHDOLEK I haven’t had a single entry where the xml didn’t parse, possibly due to the nature of the xml being generated from their database every 24h (for the new entries). But I suppose if you had a bad xml parser you might encounter non data related problems :D

**Comment by manami-project** [comment]
@Xetera First of all thank you for reaching out. I'm glad that this database is useful to you. That was my intention and the reason why I shared it. However this database already contains all the data that are sufficient for me. So since I won't need a character data, neither will I add character data to the current database not will I create a new one for character data.
I don't have the time to help you with this, but I am glad to see you guys helping each other on this topic.

**Comment by DonaldTsang** [comment]
Hello, anyone home?
