### ISSUE TITLE
Redistribution under MIT for a specific part of the database

### ISSUE THREAD

**Issue by irfan-dahir** [manami-project/anime-offline-database#20]
Hey, I've been following this repository for a while. Great work and thank you for your hard work!

I'm interested in a specific part of this database that **I would like to redistribute under MIT License**. Will definitely provide credits where due.

I'm looking into creating a repository specifically for relational IDs for anime and manga - which would be integrated with my own project (API service). If you're okay with it, I'd like to utilize this database for that purpose. Though I will have my own service workers populating the repository as well, this database would save me a lot of time initially.

I'm only interested in this part;
```
            "sources": [
                "http://anilist.co/anime/1535",
                "https://anidb.net/a4563",
                "https://animenewsnetwork.com/encyclopedia/anime.php?id=6592",
                "https://kitsu.io/anime/1376",
                "https://myanimelist.net/anime/1535"
            ],
```

The data above would be restructured/optimized to something better suited for my API. e.g;
```
{
	"anilist": "1535",
	"anidb": "a4563"
}
```

Let me know if you're okay with that, thanks!

**Comment by manami-project** [comment]
Hi @irfan-dahir,
thank you for reaching out and asking about this matter.
To be honest I'm not okay with that. I chose a strong copyleft license for a reason. Please consider using the latest AGPL.

**Comment by irfan-dahir** [comment]
Hey, thanks for your response. I respect your decision. Thanks again for your work!
