### ISSUE TITLE
Introducing a merge lock?

### ISSUE THREAD

**Issue by manami-project** [manami-project/anime-offline-database#23]
With this weeks update I noticed another unjustified merge which resulted in an entry having two anidb links. This is a direct result of my decision making the merge logic fuzzy for the duration (#19).

https://anidb.net/anime/7045
https://anidb.net/anime/7260

The difference in the duration is a minute. So I can assume that there might have been more unjustified merges like this. The probability is very high, because if I remember correctly around 4000 entries were affected by that change.

**First thing I want to do is revert the change and make the merge logic strict again. This will definitely take place within the next days.**

However I also have your feedback in mind that you guys seek a higher merge density. I thought about it today and this is just an idea. I neither say that I will realize it nor that I have thought everything through, but here is what I thought about.

Currently the merge is done with each update. My idea is to introduce a 'merge lock'. This would be an extra meta file that tells the merge logic to just put specific entries together if they are in that list. The rest would be handled dynamically as it is now the case. This was inspired by the rest-api project by @BeeeQueue.
The `merge-lock.json` could look like this:
```
[
  [
    https://anidb.net/anime/2880,
    https://kitsu.io/anime/4761,
    https://myanimelist.net/anime/6868
  ]
]
```
It doesn't have to contain ALL entries. It just says that if entries are in one array together, then those will definitely be merged together. The rest will be handled using the default merge logic.
That is a lot of manual work and I cannot do that. **So I would need you guys to create PRs and fill that file.** With each weekly update I could provide another file which contains all anime that havent't been merged and the reason why merging has been prevented. Such a file could look like this:

```
Year [1993] does not match [1992]. Not merging [https://anidb.net/anime/3172, https://animenewsnetwork.com/encyclopedia/anime.php?id=4405] into [https://kitsu.io/anime/12337, https://myanimelist.net/anime/32628].
Duration [1800]seconds does not match [1500]seconds. Not merging [https://anilist.co/anime/6868] into [https://anidb.net/anime/2880, https://animenewsnetwork.com/encyclopedia/anime.php?id=1481, https://kitsu.io/anime/4761, https://myanimelist.net/anime/6868].
```

Additional thoughts and points:
+ Should the merge-lock contain only these 'override' style rules or should every merge be locked? (see **EDIT1**)
+ 1-on-1 array or all entries within one array? (has to be dealt with, unresolved)
+ What about duplicates? (see **EDIT2**)
+ What about entries that have been deleted? (see **EDIT2**)

We are talking about >7000 merge lock entries here. So I would really need help on this.
So I'd love to hear your thoughts on this whole concept.
And just to be clear:
I will definitely go back to strict merging rules and **it is completely uncertain whether or not I will approach the merge density with an idea such as I state above or if I leave it as it was before.**

### EDIT1
To keep it simple we should start with only merge-locks for everything that is listed in the merge prevention list.

### EDIT2
In my opinion it is fine to merge duplicates since the merge is correct. We cannot say for sure which of the duplicates will be removed and when. As soon as a duplicate is removed nothing will happen anyway. That brings me to the second point. I think that it wouldn't be necessary to handle removed source links. The respective entries will never pass the merge lock again. The meta file `merge-lock.json` might contain some dead links, but that is not critical in my opinion. The merge was correct at some point and it won't have any effect on future merges. There are only unnecessary entries in the file, but I doubt that dead entries would increase the file size tremendously. However removing dead entries could be done automatically later on.

**Comment by floflo2607** [comment]
I think that's very good, it's the best thing to do I think.

**Comment by BeeeQueue** [comment]
I am obviously biased towards this solution 😉 

Only override rules should be necessary, locking every entry would be overkill.

1-to-1 makes more sense if most of the failed merges are small (only anidb didn't merge into an entry with 3 other links), while the other one is safer but takes more space.

Does merging duplicates mean you can get multiple links per website? e.g. two anidb links

Deleted entries should be removed automatically, now or in the future

**Comment by manami-project** [comment]
@floflo2607 thanks for the rapid feedback. I appreciate it!


@BeeeQueue thank you for your feedback
> I am obviously biased towards this solution wink

Obviously ;)

> Only override rules should be necessary, locking every entry would be overkill.

Exactly. That's what I tried to express in my EDIT1. Every entry would be a possibility and could be partially automated, but it's unnecessary and as you said: overkill.

> 1-to-1 makes more sense if most of the failed merges are small (only anidb didn't merge into an entry with 3 other links), while the other one is safer but takes more space.

I tend towards the safe version. The file size is negligible. It wouldn't be bigger than the database file and the only operation that uses it is the script.

> Does merging duplicates mean you can get multiple links per website? e.g. two anidb links

Yes. There are always cases of duplicated anime. Currently myanimelist is the one with the most. Just as an example... there are currently four entries for _Cooking with Valkyries_. This can happen if the anime titles are created, but the mods didn't approve them yet. That is different for anbidb. On anidb unapproved anime are not available. And of course it's possible that there are approved duplicates, because mistakes can happen ;)

> Deleted entries should be removed automatically, now or in the future

For the `anime-offline-database.json` this is already the case. This would even be the case if an entry is listed in the `merge-lock.json`. It would then be removed from the  `anime-offline-database.json`  anyway. Only the `merge-lock.json` might contain some zombies entries. But I don't think that this is critical, because it's only be a meta file for the automated process and not meant to be used by users. So this is something that could be fixed later on.

**@ all**
Any other thoughts? Is there anyone who can say that he or she would be at least interested in contributing?

**Comment by manami-project** [comment]
I've added the whole merge lock stuff and updated the contribution guidelines.
