### ISSUE TITLE
Clarification about merge preventions and locks

### ISSUE THREAD

**Issue by jilljenn** [manami-project/anime-offline-database#31]
Hi, thanks for this awesome project!
Maybe this is just about vocabulary, but I don't get how preventions and locks are related.

Preventions means: should not merge, right?
And locks means: should merge, right?

By the way, thanks to our own database I think we managed to isolate merge suggestions for the anime offline database. See more in [this notebook](https://github.com/mangaki/notebooks/blob/master/V%20-%20Unification%20des%20IDs.ipynb).

It's not perfect yet, as for example all Kara no Kyoukai movies correspond to the same AniDB ID, but you might want to consider them separately.

**Comment by manami-project** [comment]
Hi @jilljenn,
that is about right. The merge process did not merge the entries in the merge preventions file. Using a merge lock you can overrule this decision and merge them anyway.
Currently I am using deterministic record matching. However last week I decided to experiment with probabilistic record matching.

Interesting. I'll have a look at your notebook.

**Comment by jilljenn** [comment]
Yes, thanks! Will try to submit something soon.
