### ISSUE TITLE
Incorrect synonym for Haikyuu!!: Lev Genzan!

### ISSUE THREAD

**Issue by jilljenn** [manami-project/anime-offline-database#35]
A subtle one that may require its own issue:

**Haikyuu!!: Lev Genzan!** https://myanimelist.net/anime/25303  
in Manami, has in its synonyms both:  
Haikyuu!!: Jump Festa 2014 Special  
and  
Haikyuu!!: Jump Festa 2015 Special

But it is the 2014 Special, not 2015 Special (which is another one, already in Manami).

**Comment by manami-project** [comment]
This is due to the synonyms on the kitsu page: https://kitsu.io/anime/8626
Both synonyms for 2014 and 2015 are listed there.
You can report database changes on kitsu [here](https://kitsu.io/feedback/database-requests)
