### ISSUE TITLE
Does Anime News Network count as a datatbase?

### ISSUE THREAD

**Issue by DonaldTsang** [manami-project/anime-offline-database#37]
Since ANN has data on both community ratings and "encylopedia" data, would it be considered for this database?

**Comment by manami-project** [comment]
Hello @DonaldTsang,

thank you for your interest in the project.
The wording I use here which would apply to ann is "meta data provider" instead of "database".
I started adding different meta data providers, because I wanted to be able to switch the links for my personal anime list from one meta data provider to another. I don't plan to add ann to this database because it is currently not a meta data provider I consider switching to.

**Comment by DonaldTsang** [comment]
@manami-project care to define what is "meta data" in the context.

**Comment by manami-project** [comment]
Descriptive meta data such as title or number of episodes.

**Comment by DonaldTsang** [comment]
I do think that they have metadata such as:
- alternate titles, titles in multiple languages
- voice actors, writers, artists, and staff
- list of episodes and runtime
- related media
- genre and themes
- summary

Here are some examples (some of my preferences):
- https://www.animenewsnetwork.com/encyclopedia/anime.php?id=49 (EVA)
- https://www.animenewsnetwork.com/encyclopedia/anime.php?id=299 (G Gundam)
- https://www.animenewsnetwork.com/encyclopedia/anime.php?id=1177 (Enders)
- https://www.animenewsnetwork.com/encyclopedia/anime.php?id=2259 (Rockman EXE)
- https://www.animenewsnetwork.com/encyclopedia/anime.php?id=4576 (Nanoha)
- https://www.animenewsnetwork.com/encyclopedia/anime.php?id=4797 (Eureka)
- https://www.animenewsnetwork.com/encyclopedia/anime.php?id=5378 (Otome)
- https://www.animenewsnetwork.com/encyclopedia/anime.php?id=8586 (Macross)
- https://www.animenewsnetwork.com/encyclopedia/anime.php?id=11769 (Stratos)
- https://www.animenewsnetwork.com/encyclopedia/anime.php?id=12198 (T&B)
- https://www.animenewsnetwork.com/encyclopedia/anime.php?id=12868 (Horizon)
- https://www.animenewsnetwork.com/encyclopedia/anime.php?id=13251 (Muvluv)
- https://www.animenewsnetwork.com/encyclopedia/anime.php?id=13659 (Symphogear)
- https://www.animenewsnetwork.com/encyclopedia/anime.php?id=13809 (Smile Precure)
- https://www.animenewsnetwork.com/encyclopedia/anime.php?id=15000 (Neptunia)
- https://www.animenewsnetwork.com/encyclopedia/anime.php?id=19850 (Franxx)

**Comment by manami-project** [comment]
I didn't question that.

**Comment by DonaldTsang** [comment]
So in a sense, ANN does not order their data properly, is that it?

**Comment by manami-project** [comment]
No. As I stated
> I started adding different meta data providers, because I wanted to be able to switch the links for my personal anime list from one meta data provider to another. I don't plan to add ann to this database because it is currently not a meta data provider I consider switching to.

So I only add data that I personally need and I only add meta data providers that I consider using. ANN is not a site that I consider using myself.

**Comment by DonaldTsang** [comment]
In that case a PR would suffice?
