### ISSUE TITLE
Possible Extension: Character databases

### ISSUE THREAD

**Issue by DonaldTsang** [manami-project/anime-offline-database#38]
Here are some websites that have data on Anime characters:
- Anime Database supplements
  - https://www.anime-planet.com/characters/asuka-langley-soryu
  - https://anidb.net/character/39
  - https://www.absoluteanime.com/neon_genesis_evangelion/asuka (anime database not in API)
- General-purpose http://www.animecharactersdatabase.com/characters.php?id=10712
- Waifu wars https://mywaifulist.moe/waifu/asuka-langley-soryu-neon-genesis-evangelion
- Personality https://www.personality-database.com/profile/4173/asuka-langley-soryu-neon-genesis-evangelion-mbti-personality-type

I would like to ask for pointers to other repos, or ways to implementing such a database with the AOD as a basis.

**Comment by manami-project** [comment]
Maybe this post can help you: #17
I cannot help you with "ways to implement such a database". That is very general and depends on a lot of things. From my perspective this is more suited for a forum or the like, rather than this issues section.
