### ISSUE TITLE
AniDB Title Synonyms/Shorts are not populated

### ISSUE THREAD

**Issue by runecalico** [manami-project/anime-offline-database#40]
The Synonyms and Shorts from AniDB are not being populated in the offline database.

I am not knowledgeable in either the process used to generate the file nor the language, however it seems like the process is using a web scraper, and I noticed that on the AniDB website Synonym and Shorts are capitalized, while the search code seems to have all lower case.  Is that web scrape case sensitive?

Two examples that have a number of synonyms and/or shorts to illustrate ..
https://anidb.net/anime/15146
https://anidb.net/anime/15283

Is the process used to generate the AOD using the generated title xml that AniDB regularly updates? https://wiki.anidb.net/API - File is  http://anidb.net/api/anime-titles.xml.gz.   I don't know if using that might help if it's not currently being used as it avoids the whole web scraping thing (which irritates the anidb mods from what I can tell), and might be faster then the normal http requests for all that stuff. It only has titles and AID, so it can't really help with any data beyond that.

**Comment by manami-project** [comment]
Fixed. Thank you very much for reporting this.

**Comment by runecalico** [comment]
Awesome. Thanks for the quick response.
