### ISSUE TITLE
Incorrect Entry

### ISSUE THREAD

**Issue by samyak-jain** [manami-project/anime-offline-database#45]
Looks like the following mapping is not done correctly:

```
{"anilist":null,"anidb":15335,"myanimelist":null,"kitsu":null}
```

and 

```
{"anilist":114236,"anidb":null,"myanimelist":40956,"kitsu":42909}
```

despite them referring to the same show.

**Comment by samyak-jain** [comment]
It looks like this also applies to all seasons of oregairu.
For example:

```
{"anilist":14813,"anidb":null,"myanimelist":14813,"kitsu":7169}
```

and 

```
{"anilist":null,"anidb":9310,"myanimelist":null,"kitsu":null}
```

**Comment by manami-project** [comment]
Hello @samyak-jain ,

thank you for your interest in this project. Those entries are not merged together. This is strictly speaking not incorrect. I've added [FAQ](https://github.com/manami-project/anime-offline-database/blob/master/.github/CONTRIBUTING.md#there-are-duplicates-in-the-data-set) which also explain why this is not considered incorrect. It is not ideal, but not incorrect. Maybe I can find the time to fix those specifically.

**Comment by samyak-jain** [comment]
Hey. Thanks for the response. Sorry for not reading the FAQ. I have some quick questions. 
I was a bit confused about what you meant by this:

> However the intended usage is to query by the url of the meta data provider. This way you will always retrieve the entry that you want. Entries being merged together is just a nice to have.

Reading the FAQ, I got the impression that this issue is only supposed to happen if you query by title and not when you query by url. However, I got the above response using the id from the url. Am I misunderstand what you're trying to say? Also, you mention that the entries being merged together is a nice to have but I was under the impression that cross referencing between different providers was the main goal of this project. Am I mistaken?

Also, I was previously under the assumption that this data was manually curated but reading the FAQ seems to suggest that you are automatically generating the data. Can you provide some insight into how you are merging all the entries? Based on that, I can probably tweak whatever heuristic you are using so that I can be more aggresive in my merge. I understand why you wouldn't take this approach but am curious if it is possible for me to change things on my side.

Thanks for the project!
