### ISSUE TITLE
Database usage & AGPL license

### ISSUE THREAD

**Issue by koji98** [manami-project/anime-offline-database#47]
Hey, I was a little confused during my research so thought it would be best to ask here. With the AGPL license this database is under, what am I allowed to do? I would like to query this database simply to map anime between different providers and possibly use the tags for a closed-source project. Is this fine?

**Comment by Animenosekai** [comment]
According to GitHub:

> Permissions of this strongest copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.

I guess that you can use it to map the different providers and also for your closed-source projects ("Private Use", "Commercial Use") but you need to make sure to keep the same license, state the changes that you've made, License and copyright notice and give the original source code.

By the way, if you don't want to download the database just to map the different providers, check out [BeeeQueue/arm-server](https://github.com/BeeeQueue/arm-server) (and its API https://relations.yuna.moe) which lets you do exactly what you are looking for through the API (you give it an ID and its source, and it returns the other providers)

Also, I'm not @manami-project so we should also wait for an answer from him.

**Comment by koji98** [comment]
Thanks for the feedback! @Animenosekai Using the API you mentioned would probably be the easiest course of action.

**Comment by manami-project** [comment]
Hi @koji98,

from what I understand your question is obsolete now, because you want to use a different project anyway. Is that correct?

**Comment by runecalico** [comment]
<doh> I don't know why I didn't think to ask this question myself.

I am using the database file, along with the AniDB Title XML to generate an xml file that has unique synonyms for AniDB Titles, with some liberal data matching of anidb entries to non-anidb entries in AOD.  The generated file only has the synonym data from AOD and none of the other metadata from it.   As it uses AOD, this probably falls under a derivative work?

https://github.com/runecalico/filebot-public/blob/main/datafiles/anime-synonyms.xml

So I'd need to include the AGPL license file, does it need to be at the root of the repo, or can it be in the same folder as the xml. I would also expect I need to give some kind of attribution, do you have a link on some kind of expected boilerplate etc?

The Script to generate it is also there: 
https://github.com/runecalico/filebot-public/blob/main/scripts/generate_anidb_synonyms_from_aod.groovy

**Comment by koji98** [comment]
Yeah that's correct @manami-project

**Comment by manami-project** [comment]
Hi @runecalico,

first of all the disclaimer: I'm not a lawyer and I cannot and will not give legal advice.

> So I'd need to include the AGPL license file, does it need to be at the root of the repo, or can it be in the same folder as the xml.

My understanding is that the license doesn't make any strict regulations on where to place the license file, not even in the section "How to Apply These Terms to Your New Programs".

> I would also expect I need to give some kind of attribution, do you have a link on some kind of expected boilerplate etc?

No, I didn't prepare anything to be copy&pasted for attribution and I don't plan to prepare andything.
