### ISSUE TITLE
Can be added description field?

### ISSUE THREAD

**Issue by evgeniy55** [manami-project/anime-offline-database#48]
I would like field the description for not to open the links to sites, and  read description in the database.

**Comment by manami-project** [comment]
Please read the [FAQ](https://github.com/manami-project/anime-offline-database/blob/master/.github/CONTRIBUTING.md#can-you-please-add-additional-information) before posting.
Especially for synopsis/description: I won't add them as they are not public domain and you cannot merge them.
Opening the links to get additional information is part of the concept of this dataset.

**Comment by evgeniy55** [comment]
I see, Sorry
