### ISSUE TITLE
Dub tag

### ISSUE THREAD

**Issue by frederik2000x** [manami-project/anime-offline-database#50]
could you add a tag if it’s dubbed or not

Please read the [FAQ](https://github.com/manami-project/anime-offline-database/blob/master/.github/CONTRIBUTING.md#faq) first.

**Comment by manami-project** [comment]
Hi @frederik2000x,

I don't add tags myself. The data itself is taken from the supported meta data provider only. If you want tags to be added then they are the best place to ask for it.

**Comment by frederik2000x** [comment]
> Hi @frederik2000x,
> 
> I don't add tags myself. The data itself is taken from the supported meta data providers only. If you want tags to be added then they are the best place to ask for it.

Thats not what I meant. To example animeplanet has a dubbed tag, but its not listet below tags. its a category on its own.
https://www.anime-planet.com/anime/all?en_dub=1

**Comment by manami-project** [comment]
So you don't mean a value in the property "tags", but a new property in the JSON?
Please read the FAQ before posting. [It has already been answered](https://github.com/manami-project/anime-offline-database/blob/master/.github/CONTRIBUTING.md#can-you-please-add-additional-information).

**Comment by frederik2000x** [comment]
@manami-project 
anime-planet put it in an extra category. I asked if you could add this to the tags, because of that reason

**Comment by manami-project** [comment]
Now I think I get what you mean.
anime-planet categorizes anime by "English dubbed". And if that's the case you want this to be added to the tags property.
I don't see a possibility to do that though, because that info can't be extracted from the anime details page.
If it's not on the details page then it would be too much of a hassle to add.
