### ISSUE TITLE
A peculiar property of cross links to anidb

### ISSUE THREAD

**Issue by MeRuslan** [manami-project/anime-offline-database#54]
I've been mapping songs from anidb to mal anime ids, and discovered something about links to anidb entries. Some of them do not appear in manami, which is not the issue.

However, there seems to be an improvement potential, unmapped anidb anime titles all seem to be marked 18+. The thing is, anidb does not show them unless you are logged in and confirm you are over 18 y.o.

Here are some of those anidb ids for reference: 
`manami missing ids {'1640', '1847', '1166', '1278', '1546', '2803', '9549', '5358', '1492', '11194', '1426', '6002', '6765', '1876', '2748', '11182', '15258', '14102', '7984', '13384', '1556', '8814', '4544', '1844', '12157', '1522', '249', '6189', '1212', '1626', '8911', '4848', '5633', '1557', '307', '2566', '14252', '1629', '4981', '3289', '3982', '2747', '2552', '308', '2032', '5543', '13170', '4735', '2029', '7929', '2148', '1982', '2485', '2565', '549', '5203', '5359', '1333', '1328', '6484', '6817', '300', '9276', '851', '9469', '6561', '1088', '1396', '663', '664', '10942', '9699', '7259', '4347', '4443', '13652', '10504', '6208', '8994', '677', '4423', '1405', '174', '119', '15697', '12005', '7037', '907', '13761', '10263', '14340', '1047', '13411', '8262', '11085', '9933', '1603', '1987', '5594', '10296', '15510', '4078', '2254', '8402', '2141', '2145', '2571', '1875', '12547', '1624', '2573', '8473', '13550', '5205', '1628', '13285', '5541', '1627', '10964', '12512', '559', '12699', '700', '2567', '5031', '11047', '7030', '933', '1062', '1042', '12596', '1974', '849', '13489', '1168', '1420', '1510', '6154', '3527', '2373', '13356', '1843', '7915', '5200', '3999', '4493', '7489', '6675', '11476', '1338', '5362', '802', '1347', '8795', '2027', '10893', '1410', '10793', '7303', '2570', '267', '1642', '13251', '15630', '1108', '1720', '10839', '6781', '839', '1970', '8837', '1665', '4304', '2515', '3452', '1752', '2502', '2563', '6554', '667', '3531', '13834', '1337', '357', '1547', '7519', '1133', '1509', '5848', '7566', '243', '4155', '8508', '1159', '2268', '3537', '10221', '5889', '2804', '1346', '1694', '4075', '1207', '1331', '985', '5912', '5836', '2561', '870', '5193', '1433', '4823', '2701', '10189'}
`

**Comment by MeRuslan** [comment]
Not sure this behavior is intentional or desired, because the same titles from MAL are likely included (checked some of them).
With the difference being, MAL does not require you to be logged in.

**Comment by manami-project** [comment]
See [FAQ - "Does this dataset contain all anime from the supported meta data provider?"](https://github.com/manami-project/anime-offline-database/blob/master/.github/CONTRIBUTING.md#does-this-dataset-contain-all-anime-from-the-supported-meta-data-provider)

**Comment by MeRuslan** [comment]
I see, sorry to have missed that one.

**Comment by MeRuslan** [comment]
Just to be sure, so, no plans to catalogue those that need authentication?

**Comment by manami-project** [comment]
> Just to be sure, so, no plans to catalogue those that need authentication?

Yes, that is correct.
