### ISSUE TITLE
Some missing entries

### ISSUE THREAD

**Issue by germancasares** [manami-project/anime-offline-database#58]
| Kitsu | AniDB | AniList | MyAnimeList |
|-------|-------|---------|-------------|
| 46100 | 17352 | 148401  | 51772       |
| 44974 | 16533 | 137819  | 49590       |
| 46010 | 17286 | 146722  | 51367       |
| 46020 | 17239 | 146885  | 51263       |
| 44397 | 16081 | 130389  | 48375       |
| 44294 | 16187 | 131942  | 48661       |

**Comment by manami-project** [comment]
Hi @germancasares,

some context would be helpful. Which entries are missing?
I only checked the last row of your table. It seems that each row indicates exactly one anime and its IDs of the respective meta data providers.

The entry I checked however exists with all of the IDs mentioned in the table.
 
```json
 {
      "sources": [
        "https://anidb.net/anime/16187",
        "https://anilist.co/anime/131942",
        "https://anime-planet.com/anime/jojos-bizarre-adventure-stone-ocean",
        "https://anisearch.com/anime/16162",
        "https://kitsu.io/anime/44294",
        "https://livechart.me/anime/10512",
        "https://myanimelist.net/anime/48661",
        "https://notify.moe/anime/m26yPJ_Gg"
      ],
      "title": "JoJo no Kimyou na Bouken Part 6: Stone Ocean",
      "type": "ONA",
      "episodes": 12,
      "status": "FINISHED",
      "animeSeason": {
        "season": "FALL",
        "year": 2021
      },
...
```

Can you clarify this for me?

**Comment by germancasares** [comment]
Yes sorry, I did a mistake and was avoiding all the animes that were not type TV.

My bad. Thanks for doing this database! It is super useful!
