### ISSUE TITLE
Can you add synopsis/description?

### ISSUE THREAD

**Issue by iTaishi** [manami-project/anime-offline-database#59]
Hi,

can you add a field synopsis/description to an Anime?

Best regards

**Comment by manami-project** [comment]
https://github.com/manami-project/anime-offline-database/blob/master/.github/CONTRIBUTING.md#can-you-please-add-additional-dataproperties

https://github.com/manami-project/anime-offline-database/issues/48

https://github.com/manami-project/anime-offline-database/issues/30
