### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by mibj** [manami-project/anime-offline-database#60]
* Which data is not extracted correctly? (e.g. title, episodes...)
Download json on 24/12/2022

item[601]  Title : 'Ai Tenshi Densetsu Wedding Peach'
synonyms[8] :  'Wedding Peach: I tanti segreti di cuore innamorato'

* Can you provide an example entry?

* Which value is expected?
you should replace  :

'Wedding Peach: I tanti segreti di cuore innamorato'

with:

'Wedding Peach: I tanti segreti di un cuore innamorato'

difference : 'un'  

Happy Holidays and Thank you for your work  !

**Comment by manami-project** [comment]
Hi @mibj,

the extraction of the data is correct. The source of the mentioned entry in synonyms is https://anisearch.com/anime/1279.
I don't modify the data. It is taken as-is. So if you want it to be changed, please contact anisearch directly.
