### ISSUE TITLE
2022-12-21  Data Entry  ' Blue Dragon 2'

### ISSUE THREAD

**Issue by mibj** [manami-project/anime-offline-database#61]
Last update 2022-12-21

$.data.[2681].synonyms.[1]
it's not 'Blue Dragon' but it should be only 'Blue Dragon 2'
Should you delete 'Blue Dragon' synonyms ?

Blue Dragon is from 2007 year
Blue Dragon 2 is from 2008 year

Happy Holidays

**Comment by manami-project** [comment]
Hi @mibj,

you should use the `sources` property to identify entries (see [FAQ](https://github.com/manami-project/anime-offline-database/blob/master/.github/CONTRIBUTING.md#why-are-there-no-ids).

The extraction of the data is correct. The source of the mentioned entry in synonyms is https://anisearch.com/anime/4847.
I don't modify the data. It is taken as-is. So if you want it to be changed, please contact anisearch directly.
