### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by PhoneDroid** [manami-project/anime-offline-database#62]
I would like to contribute TypeScript definitions for the database structure, in general it would seem helpful to provide a folder for different typed languages ( in case other people would want to define them for other languages)

While I'm aware your project uses Kotlin, I don't think it would hurt to allow definitions for other languages, considering they are only modeled after your structure and don't change anything, which you don't seem to want.

**Comment by manami-project** [comment]
I'm not entirely sure if my understanding of your idea is correct.
To me it sounds like you suggest to add a folder (e.g. "type-definitions") containing a subfolder for different programming languages (e.g. "typescript"). In it you would place language specific definitions for objects. For example `*.ts` files containing interface definitions?

Is my understanding of your idea correct?

**Comment by PhoneDroid** [comment]
Yes, definitions of your database files, as an extension to the README explanation of the database structure.

**Comment by manami-project** [comment]
I don't really see the necessity or the benefit.
The repo is currently language-neutral and I'd like to keep it that way.
The object structure is not complex, doesn't contain that many properties and is well documented.
So creating the objects in your preferred language shouldn't be a time consuming task.

If you still see any benefit for it, I would suggest that you create a repo that contains the
language specific type definitions and maybe even a parser. That's what I did for kotlin as well.
