### ISSUE TITLE
Is there a way to improve extraction from anidb, anilist and kitsu

### ISSUE THREAD

**Issue by Py-Monsters** [manami-project/anime-offline-database#63]
First of all, thank you for creating this database. It has helped me a lot.

Recently, I noticed that few anime on anidb, anilist and kitsu are not available in the database. After further investigation, I found out that you be get them unless you are using an API (with authentication for kitsu.io) or you are logged in.
As of now:
Anidb has 14164 (only 12716 included in the database)
Anilist has 18547 (only 17010 included in the database)
Kitsu has 20248 (only 18713 included in the database)

Anidb info is provided by the site at the home page (I also checked programmatically)
Anilist and Kitsu infos are provided by their API

Thank you,

**Comment by manami-project** [comment]
**FAQ:** [Does this data set contain all anime from the supported meta data provider?](https://github.com/manami-project/anime-offline-database/blob/master/.github/CONTRIBUTING.md#does-this-data-set-contain-all-anime-from-the-supported-meta-data-provider)

If apart from that entries are missing over a course of multiple weeks, you can create new issue "Problem in data extraction" with examples.

**Comment by Py-Monsters** [comment]
Sorry, I didn't check that.
Also, regarding anidb, how do you bypass the AntiLeech?
