### ISSUE TITLE
Extraction question

### ISSUE THREAD

**Issue by Py-Monsters** [manami-project/anime-offline-database#64]
Why do you use the site over the API provided to extract the data? I tried to extract from both the API and the site (MAL, Anilist, Kitsu) and found that their APIs are much faster compared to the site.
MAL API takes around 1 second to get 500 anime (1 page) (with all information excluding pictures, background, related_anime, related_manga, recommendation, statistics) 
Anilist API takes less than 1 second to get 50 anime (1 page) (with all information, is the slowest because of rate-limiting)
Kitsu API takes around 0.5 seconds to get 20 anime (1 page) (with all information, more information may take more time, for all possible fields it took between 0.5 and 1 second to get 1 page)
I made a code for all of the shown providers to time them, and here are the results:
MAL API: 10s-30s
Anilist API: ~4m (because of rate-limiting)
Kitsu API: 35s-60s

So what are the advantages of using the site itself over the API?

**Comment by manami-project** [comment]
It seemed the best solution for me when I made the decision.
So far I'm fine with it.
