### ISSUE TITLE
Legal issues

### ISSUE THREAD

**Issue by Majticz** [manami-project/anime-offline-database#67]
Do/Can you get in legal issues with the providers for downloading their data?

**Comment by manami-project** [comment]
My assumption is that you are asking for your own project and rather want to know if your project could get any issues.
I'm not lawyer, but I don't see any problem with my project. Your project is different and created differently so you have to answer this question regarding your project yourself.

**Comment by Majticz** [comment]
Thanks. Also, it's not specifically about my project. I am using my project side to side with this one.
