### ISSUE TITLE
dub data extraction

### ISSUE THREAD

**Issue by singersbalm** [manami-project/anime-offline-database#70]
I have a suggestion to extract the dub data from the pages. I would suggest even though its not listed as a tag on these pages to add it as a tag. For example english-dub, german-dub, french-dub etc.
this can be extracted from anisearch, kitsu, anime-planet, anilist and myanimelist. Below are screenshots where to find it on the webpages. 
<img width="1440" alt="Screenshot 2023-10-19 at 4 33 57 PM" src="https://github.com/manami-project/anime-offline-database/assets/122386799/aca4c998-cc6b-43b9-b908-45c738b47695">
<img width="1440" alt="Screenshot 2023-10-19 at 4 41 55 PM" src="https://github.com/manami-project/anime-offline-database/assets/122386799/ad8a1087-3023-49c7-ad52-a3935484b284">
<img width="1440" alt="Screenshot 2023-10-19 at 4 37 15 PM" src="https://github.com/manami-project/anime-offline-database/assets/122386799/a1312c3c-9af2-45fe-b3fb-2d21e72073fc">
<img width="1440" alt="Screenshot 2023-10-19 at 4 35 47 PM" src="https://github.com/manami-project/anime-offline-database/assets/122386799/7f211bc0-8244-4bf5-845a-b12d20c46288">
<img width="1440" alt="Screenshot 2023-10-19 at 4 34 13 PM" src="https://github.com/manami-project/anime-offline-database/assets/122386799/785ea489-a4f7-45c2-a828-5853b372d558">

**Comment by manami-project** [comment]
I don't see any benefit.
