### ISSUE TITLE
2 duplicates

### ISSUE THREAD

**Issue by singersbalm** [manami-project/anime-offline-database#72]
//duplicate 1
https://anidb.net/anime/12049
https://anilist.co/anime/21734/Buddy-Go/

//duplicate 2
https://anidb.net/anime/4576
https://anilist.co/anime/210/Ranma-12/

**Comment by manami-project** [comment]
# Report 1
Please read the FAQ first: [FAQ on duplicates](https://github.com/manami-project/anime-offline-database/blob/master/.github/CONTRIBUTING.md#there-are-duplicates-in-the-data-set)

# Report 2
Thanks for reporting that. It will be changed in the next update.
