### ISSUE TITLE
"https://anidb.net/anime/18144",   "https://anidb.net/anime/15538",   "https://anilist.co/anime/163544",   "https://anisearch.com/anime/18594"

### ISSUE THREAD

**Issue by singersbalm** [manami-project/anime-offline-database#74]
"https://anidb.net/anime/18144",
  "https://anidb.net/anime/15538",
  "https://anilist.co/anime/163544",
  "https://anisearch.com/anime/18594"

**Comment by manami-project** [comment]
No context, use the existing issue templates. I don't see why these four entries should be merged together.
