### ISSUE TITLE
One piece anime

### ISSUE THREAD

**Issue by mentor1th** [manami-project/anime-offline-database#75]
One piece anime have bad anime in tags.. Toriko is not one piece and have dragonball same:D

**Comment by manami-project** [comment]
I need more info. Which entry are you refering to (please post the entry or the `source` property) and which tag in that entry is missing?

**Comment by mentor1th** [comment]
MAL link: https://myanimelist.net/anime/21/One_Piece

Dragonball Z and Toriko only Recommendations from users, but in your json file this 2 anime in tags.

**Comment by manami-project** [comment]
Now I understand what you try to point out. Your message is misleading. You don't mean entries in tags.
What you mean is that `https://myanimelist.net/anime/10033` and `https://myanimelist.net/anime/813` are listed in **relations** which in your opinion should not be the case.

If you look at https://myanimelist.net/anime/21 you can see that both entries are listed under **Related Anime** and then within the list of **Character**. This works as designed. I assume that characters from that series appear in the aforementioned entries.
