### ISSUE TITLE
Algorithm for matching entries

### ISSUE THREAD

**Issue by Garakusi** [manami-project/anime-offline-database#77]
I've read in the FAQ that you intent to release the full source for the code that generates the MODB. I'm particularly interested in the algorithm that matches entries from different meta data providers. How long it will take for it to be released?
Context: I'm working in a similar project and this task is fairy complicated, my current solution is not very accurate.

**Comment by manami-project** [comment]
I cannot say how long it will take. I'm strictly speaking not working on it very actively.
See also #65 #32
