### ISSUE TITLE
Is there an anime score?

### ISSUE THREAD

**Issue by Theldus** [manami-project/anime-offline-database#78]
Hi,
I looked all over the repo and couldn't find it anywhere. Is there a 'score' field? I know it's a 'volatile' field, which varies according to the source used and also over time... but it seems too useful to be left aside.

A few years ago I had a mini-DB with around ~4k animes, and I was able to discover good animes to watch by filtering by genre, year of release, number of episodes and score. Unfortunately I no longer have it and I don't even remember where I got it.

So I would like to use this repo for the same purpose, but without the score field, it ends up becoming useless for me.

**Comment by manami-project** [comment]
As you can see in the `README.md`, which lists all properties, there is no field for a score.
Maybe you can find an alternative dataset here on github or try something like kaggle.com
