### ISSUE TITLE
why are the images incredibly small 

### ISSUE THREAD

**Issue by anime-kun32** [manami-project/anime-offline-database#80]

**Comment by manami-project** [comment]
Which images du you mean specifically?

**Comment by anime-kun32** [comment]
> Which images du you mean specifically?

the thumbnail and the picture 
all of them

**Comment by manami-project** [comment]
Those are created and provided by the respective meta data provider.
The data set only links to those. I cannot really answer your question at this point.

**Comment by manami-project** [comment]
If you mean `no_pic.png` and `no_pic_thumbnail.png`: Sizes of those are based on MAL image sizes.
