### ISSUE TITLE
How can I help by being a contributor here?

### ISSUE THREAD

**Issue by lucasnuic** [manami-project/anime-offline-database#81]
Hi @manami-project

I have several ideas for improvements and corrections, I would be happy if someone could guide me. And then contribute a lot here.

How can I help by being a contributor here?

**Comment by manami-project** [comment]
Hello @lucasnuic,

my suggestion would be to carefully read the [FAQ](https://github.com/manami-project/anime-offline-database/blob/master/.github/CONTRIBUTING.md) and then have a look at the [issue templates](https://github.com/manami-project/anime-offline-database/issues/new/choose) to see which three cases are available for you to contribute.
