### ISSUE TITLE
Lots of "adult" items are marked dead for Anilist

### ISSUE THREAD

**Issue by PythonCoderAS** [manami-project/anime-offline-database#85]
* Which data is not extracted correctly? (e.g. title, episodes...)

Source, title

* Can you provide an example entry? _Post the whole entry or at least the `source` property as seen in the dataset._

N/A

* Which value is expected?

Anilist's APIs do not expose data for adult content without being logged in and enabling adult content in the settings. A lot of items that exist on MAL (because MAL does not have such a gate) therefore do not have the Anilist version, despite anilist returning the linked MAL ID.

**Comment by manami-project** [comment]
FAQ: [Does this dataset contain all anime from the supported meta data providers?](https://github.com/manami-project/anime-offline-database/blob/master/.github/CONTRIBUTING.md#does-this-dataset-contain-all-anime-from-the-supported-meta-data-providers)
