### ISSUE TITLE
Is there also support SIMKL Anime ID's as well?

### ISSUE THREAD

**Issue by Azmarine13** [manami-project/anime-offline-database#87]
SIMKL Anime Page: https://simkl.com/anime/
Anime API: https://simkl.docs.apiary.io/#reference/anime

**Comment by manami-project** [comment]
Please read the [FAQ](https://github.com/manami-project/anime-offline-database/blob/master/.github/CONTRIBUTING.md#faq) before posting: [Can you please add an additional meta data provider?](https://github.com/manami-project/anime-offline-database/blob/master/.github/CONTRIBUTING.md#can-you-please-add-an-additional-meta-data-provider)
