### ISSUE TITLE
NSFW shows from aniDB marked as "dead"

### ISSUE THREAD

**Issue by ThaUnknown** [manami-project/anime-offline-database#88]
* Which data is not extracted correctly? (e.g. title, episodes...)

AniDB Hentai shows are marked as "dead entries"

* Can you provide an example entry? _Post the whole entry or at least the `source` property as seen in the dataset._

anidb aid: 15274

* Which value is expected?

this entry isnt dead, it's still on anidb

**Comment by manami-project** [comment]
[**FAQ:** Does this dataset contain all anime from the supported meta data providers?](https://github.com/manami-project/anime-offline-database/blob/master/.github/CONTRIBUTING.md#does-this-dataset-contain-all-anime-from-the-supported-meta-data-providers)
