### ISSUE TITLE
"RahXephon Kansoukyoku: Kanojo to Kanojo Jishin to - Thatness and Thereness" broken title

### ISSUE THREAD

**Issue by BonkaBonka** [manami-project/anime-offline-database#9]
First entry in the current JSON:
```
{
  "data": [
    {
      "sources": [
        "https://anilist.co/anime/559"
      ],
      "type": "OVA",
      "title": " \tRahXephon Kansoukyoku: Kanojo to Kanojo Jishin to - Thatness and Thereness",
      "picture": "https://myanimelist.cdn-dena.com/images/qm_50.gif",
      "relations": [
        "https://anilist.co/anime/165"
      ],
      "thumbnail": "https://myanimelist.cdn-dena.com/images/qm_50.gif",
      "episodes": 1,
      "synonyms": [
        "RahXephon Interlude: Her and Herself/Thatness and Thereness",
        "ラーゼフォン 間奏曲 / 彼女と彼女自身と 「Thatness And Thereness」"
      ]
    },
```

The title is broken and not merged with the kitsu.io 516 entry and/or the MAL 599, anidb a7969, ANN 3064 entry.

**Comment by manami-project** [comment]
Hi @BonkaBonka ,
thank you for taking your time reporting this.
The tab character prefixing the title of the anilist entry is actually coming from anilist itself. It seems that they actually saved the title in their database having a leading tab character. They probably copy&pasted the title from somewhere including the tab character.

Up to now I never changed any data. I have to think about whether or not I will check the titles for leading or trailing whitespace characters and trim them.

**Comment by manami-project** [comment]
Turns out there are five entries having a tab character ( \t ) and seven titles having a carriage return line feed ( \r\n ). Not only at the start or the end of a title, but inbetween as well.

Right now I don't think that this is useful. But I haven't made a decision yet.

**Comment by manami-project** [comment]
Although I don't want to change the data, It doesn't make sense to me to have escaped formatting information or multiple whitespaces in the titles.
To improve data quality I will set up the following processing on titles and synonyms:

- replace carriage return line feed ( \r\n ) with a whitespace
- replace line feed ( \n ) with a whitespace
- replace two or more whitespaces with a single whitespace
- trim titles (remove leading and trailing whitespaces)
