### ISSUE TITLE
Split https://anilist.co/anime/4024 into a new entry

### ISSUE THREAD

**Issue by Fro116** [manami-project/anime-offline-database#91]
## Which entry should be split? (original from dataset)

```
"https://anilist.co/anime/4024",
"https://anime-planet.com/anime/hello-kittys-furry-tale-theater",
"https://kitsu.app/anime/3417",
"https://myanimelist.net/anime/4024",
"https://notify.moe/anime/aQRu5Fmmg"
```

## How should it be split?

```
"https://anilist.co/anime/4024",
```

```
"https://anime-planet.com/anime/hello-kittys-furry-tale-theater",
"https://kitsu.app/anime/3417",
"https://myanimelist.net/anime/4024",
"https://notify.moe/anime/aQRu5Fmmg"
```

The entry https://anilist.co/anime/4024 refers to the 2001 series "Hello Kitty's Animation Theater". The other entries refer to the 1987 series "Hello Kitty's Furry Tale Theater". I took a quick look to see if there are any entries https://anilist.co/anime/4024 should be merged with, but didn't find any. Other sites list the episodes in https://anilist.co/anime/4024 as separate items. For example, https://myanimelist.net/anime/30263 is an episode of https://anilist.co/anime/4024.

**Comment by manami-project** [comment]
Hi @Fro116 ,
thank you for reporting this.
Should be fixed now.
